In [4]:
import tweepy
from textblob import TextBlob
from wordcloud import WordCloud
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
from google.colab import drive
drive.mount('drive')

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).

**IMPORT DATASET LABELING**

In [5]:
data = pd.read_excel('/content/dataset-labeling fix.xlsx')
data

,Unnamed: 0,tweet_cleans,tweet_english,klasifikasi
0,0,anjir wkwwkwkkw dokternya auto ngeuh,fig wkwwkwkkw the doctor auto nod,Netral
1,1,mksdnya yg ruang icu nanyain kondisi andin dok...,"i mean, the icu room asks the doctor's conditi...",Negatif
2,2,pas lahir ga nangis yaa dokternya sibuk lgi op...,"when i was born, i didn't cry, the doctor was ...",Positif
3,3,trs pas kuliah fisiologi persarafan kandung ke...,"then, when i studied physiology, the innervati...",Netral
4,4,dokternya bilang gigiku cantik ketawa,the doctor said my teeth are beautiful laugh,Positif
...,...,...,...,...
3954,4131,perawat ogut knp pasien dokternya tacut pdhl a...,"ogut nurse, why is the doctor's patient scared...",Positif
3955,4132,pas dokternya jelasin diagnosanya gw ngelamun ...,when the doctor explained the diagnosis i dayd...,Netral
3956,4133,semoga kesembuhan beb temenin makan sehat deh ...,"i hope your recovery is good, i'll eat healthy...",Netral
3957,4134,gw daritadi udah minum botol aqua ga kasian do...,i've been drinking an aqua bottle since earlie...,Positif
3958,4135,habis tht ngerasa pendengaran qoq aga berkuran...,"after that, i feel like my hearing has decreas...",Netral

**HAPUS COLUMN YANG TIDAK PERLU**

In [6]:
data.drop(['tweet_english'], axis=1, inplace=True)
data

,Unnamed: 0,tweet_cleans,klasifikasi
0,0,anjir wkwwkwkkw dokternya auto ngeuh,Netral
1,1,mksdnya yg ruang icu nanyain kondisi andin dok...,Negatif
2,2,pas lahir ga nangis yaa dokternya sibuk lgi op...,Positif
3,3,trs pas kuliah fisiologi persarafan kandung ke...,Netral
4,4,dokternya bilang gigiku cantik ketawa,Positif
...,...,...,...
3954,4131,perawat ogut knp pasien dokternya tacut pdhl a...,Positif
3955,4132,pas dokternya jelasin diagnosanya gw ngelamun ...,Netral
3956,4133,semoga kesembuhan beb temenin makan sehat deh ...,Netral
3957,4134,gw daritadi udah minum botol aqua ga kasian do...,Positif
3958,4135,habis tht ngerasa pendengaran qoq aga berkuran...,Netral

**ADA BEBERAPA YANG DUPLIKAT KARNA ITU HARUS MENJALANKAN FUNCTION DEL DUPLICATE TEXT**

In [7]:
data.drop_duplicates(subset = "tweet_cleans", keep = "first", inplace=True)
data

,Unnamed: 0,tweet_cleans,klasifikasi
0,0,anjir wkwwkwkkw dokternya auto ngeuh,Netral
1,1,mksdnya yg ruang icu nanyain kondisi andin dok...,Negatif
2,2,pas lahir ga nangis yaa dokternya sibuk lgi op...,Positif
3,3,trs pas kuliah fisiologi persarafan kandung ke...,Netral
4,4,dokternya bilang gigiku cantik ketawa,Positif
...,...,...,...
2588,2765,capek banget bisanya meluk dokternya crazylove,Negatif
2590,2767,trims mom kek gini penjelasannya aq paham dokt...,Positif
2591,2768,aaaaa merem dokternya,Netral
3275,3452,buru dibawa takut flutd gapapa kucing ku takut...,Negatif
3420,3597,kalo kucingnya steril ditaruh kamar ruang gera...,Negatif

**SIMPAN DATASET FIX**

In [8]:
data.to_excel('./dataset-label-sudah-bersih.xlsx', encoding='utf8', index=True)